[package]
name = "log-server"
version = "0.1.0"
authors = ["Makcy <644215038@qq.com>"]

[dependencies]
iron = "0.6.0"
router = "*"
bodyparser = { git = "https://github.com/iron/body-parser.git" }
chrono = "0.4.*"
